# Generated by Django 5.2.7 on 2026-02-08 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('url', 'URL')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/images/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
