# Generated by Django 5.2.7 on 2026-03-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matireals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
